package com.yk.back.service.mail;

public enum MailEvent {
    USER_WELCOME,
    PASSWORD_RESET,
    PASSWORD_CHANGED,
    LOGIN_ALERT,
    ACCOUNT_ACTIVATED,
    ACCOUNT_DEACTIVATED,
    TENANT_CREATED,
    MERCHANT_CREATED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_EXPIRED,
    INVOICE_AVAILABLE,
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED
}
